Add support for Python 3.10
oz123/pytest-localftpserver pull request #146
Opened 2021-08-24 18:20 UTC by hugovk

The main point of this PR is to add support for Python 3.10.

It may be easier to review this PR commit by commit, and please let me know if you'd prefer smaller PRs.

---

First, update the CI testing to test all supported Python versions: 3.6-3.9.

Next, add support for Python 3.10. This requires code change: `collections.Iterable` has been removed from 3.10 and has been at `collections.abc.Iterable` since 3.3.

Next, upgrade to more modern Python syntax using https://github.com/asottile/pyupgrade

Next, update docs to reflect 3.6 is the minimum supported.

Finally, drop the dot in `py.test`: https://twitter.com/pytestdotorg/status/753767547866972160

---

It would be great to get a release out for this sooner rather than later, as other libraries which depend on pytest-localftpserver cannot test/support Python 3.10 due to the `collections.Iterable` change.

Thank you!

2021-08-24 19:16 UTC, oz123 requested changes

2021-08-24 19:16 UTC, oz123 commented on docs/usage.rst
> +Tthis example utilizes methods of the the high-level interface, which are  explained in
Typo: Tt should be T?

2021-08-24 19:16 UTC, oz123 commented on docs/usage.rst
> -    import sys
Most welcome!

2021-08-24 20:07 UTC, hugovk commented on docs/usage.rst
> +Tthis example utilizes methods of the the high-level interface, which are  explained in
Yes, fixed!

2021-08-24 20:09 UTC, oz123 approved these changes

2021-08-24 20:36 UTC, merged

2021-08-25 11:24 UTC, oz123 commented
@hugovk FYI I published a new version to pypi, so you can update packages that depend on it.
I'm curious to know, which packages depend on it ?

2021-08-25 11:47 UTC, hugovk commented
Thank you!

The package which depends on it is Pooch, a file downloading app used by scientific Python projects.

* https://www.fatiando.org/pooch/
* https://github.com/fatiando/pooch

And tests now [pass for 3.10](https://github.com/hugovk/pooch/runs/3421470596?check_suite_focus=true), thanks again!